apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: wnmr65du2-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/wnmr65du2-dotnet-basic-gitops